"use client";

import { useState } from "react";
import { editPrompt, submitPrompt } from "@/app/actions/user";
import { ImageUploadField } from "@/components/image-upload-field";
import { SubmitButton } from "@/components/submit-button";
import { Input } from "@/components/ui/input";
import type { Category, Prompt } from "@/lib/types";

export function ContributeForm({ categories, initialData }: { categories: Category[], initialData?: Prompt }) {
  const [status, setStatus] = useState<"idle" | "loading" | "error">("idle");
  const [errorMessage, setErrorMessage] = useState("");

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setStatus("loading");
    setErrorMessage("");

    const formData = new FormData(e.currentTarget);
    
    let result;
    if (initialData) {
      result = await editPrompt(initialData.id, formData);
    } else {
      result = await submitPrompt(formData);
    }

    if (result?.error) {
      setStatus("error");
      setErrorMessage(result.error + (result.details ? JSON.stringify(result.details) : ""));
    }
  }

  return (
    <form onSubmit={handleSubmit} className="rounded-card border border-white/10 bg-[#090909] p-6 shadow-2xl space-y-5">
      {status === "error" && (
        <div className="rounded bg-red-500/10 p-3 text-sm text-red-500 border border-red-500/20">
          {errorMessage}
        </div>
      )}

      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Prompt Title</label>
        <Input name="title" defaultValue={initialData?.title} placeholder="e.g., Cinematic Product Commercial" className="bg-black/50 border-white/10 text-white" required minLength={3} />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Short Description</label>
        <Input name="description" defaultValue={initialData?.description} placeholder="A brief explanation of what the prompt achieves." className="bg-black/50 border-white/10 text-white" required minLength={10} />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Preview Image</label>
        <p className="text-xs text-zinc-500 mb-2">Upload an example image generated by this prompt.</p>
        <ImageUploadField name="preview_image" defaultValue={initialData?.preview_image || ""} />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Category</label>
        <select name="category_id" defaultValue={initialData?.category?.id || ""} className="w-full tap rounded-card border border-white/10 bg-black/50 px-4 h-11 text-sm text-white focus:border-accent outline-none" required>
          <option value="" disabled>Select a category...</option>
          {categories.map((category) => <option key={category.id} value={category.id} className="bg-black">{category.name}</option>)}
        </select>
      </div>
      
      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Tags (comma separated IDs)</label>
        <Input name="tags" defaultValue={initialData?.tags?.map(t => t.id).join(",") || ""} placeholder="e.g., tag1-uuid, tag2-uuid" className="bg-black/50 border-white/10 text-white" />
      </div>

      <div className="space-y-2">
        <label className="text-sm font-medium text-zinc-300">Prompt Content</label>
        <textarea name="prompt_content" defaultValue={initialData?.prompt_content} placeholder="Paste your full prompt here..." className="w-full min-h-40 rounded-card border border-white/10 bg-black/50 p-4 text-sm text-white outline-none focus:border-accent transition-colors" required minLength={10} />
      </div>

      <div className="pt-4">
        <SubmitButton className="w-full" loadingText={initialData ? "Updating..." : "Submitting..."} disabled={status === "loading"}>
          {initialData ? "Update Prompt" : "Submit for Review"}
        </SubmitButton>
      </div>
    </form>
  );
}
